#definition of all form validators
services:

    #change user password validator
    app_general.validator.constraints.change_password:
        class: App\GeneralBundle\Validator\Constraints\ChangePasswordValidator
        arguments:  [@security.encoder_factory]
        tags:
            - { name: validator.constraint_validator, alias: app_general_constraints_change_password }